name: Deploy

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: weather-app-build
          path: dist
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
           accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
           command: pages deploy dist --project-name vatavaranam

     

      - name: Deploy to Vercel
        run: |
           npx vercel deploy \
             --prod \
             --prebuilt \
             --yes \
             --token=${{ secrets.VERCEL_TOKEN }}
        env:
           VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
           VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      ##################################################
      # Deploy to AWS Amplify
      ##################################################

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Trigger Amplify Deployment
      #   run: |
      #     aws amplify start-job \
      #       --app-id ${{ secrets.AMPLIFY_APP_ID }} \
      #       --branch-name main \
      #       --job-type RELEASE